replicaCount: 2

image:
  repository: "432004895948.dkr.ecr.us-east-1.amazonaws.com/aerolink-dev/webui"
  tag: "latest"
  pullPolicy: Always

serviceAccount:
  annotations: {}     # IRSA not needed for static webui

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:432004895948:certificate/de6bd55b-79f6-4cc0-983a-d63038acbd25"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
  hosts:
    - host: ""        # e.g. aerolink.app — set in env overlay
      paths:
        - path: /
          pathType: Prefix
        - path: /api/v1/auth
          pathType: Prefix
          backendService: identity-service
          backendPort: 3000
        - path: /api/v1/users
          pathType: Prefix
          backendService: identity-service
          backendPort: 3000
        - path: /api/v1/flights
          pathType: Prefix
          backendService: flight-service
          backendPort: 3000
        - path: /api/v1/bookings
          pathType: Prefix
          backendService: booking-service
          backendPort: 3000
        - path: /api/v1/payments
          pathType: Prefix
          backendService: payment-service
          backendPort: 3000
        - path: /api/v1/checkin
          pathType: Prefix
          backendService: checkin-service
          backendPort: 3000
        - path: /api/v1/baggage
          pathType: Prefix
          backendService: baggage-service
          backendPort: 3000
        - path: /api/v1/notifications
          pathType: Prefix
          backendService: notification-service
          backendPort: 3000
        - path: /api/v1/health
          pathType: Prefix
          backendService: identity-service
          backendPort: 3000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

podDisruptionBudget:
  enabled: true
  minAvailable: 1

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: webui

env:
  VITE_API_BASE_URL: "https://api.transnova.online/api/v1"
